language: bash

addons:
  apt:
    packages:
      - bc
      - links

script:
  - ./util/requisitos.sh
  - ./testador/run funcoeszz.md
  - ./testador/run internet_travis

notifications:
  email: false
