language: bash

addons:
  apt:
    packages:
      - bc
      - links

before_install:
  - make testador/clitest

script:
  - make test-core
  - ./testador/run internet_travis

notifications:
  email: false
