language: bash

before_install:
  - url_base="https://raw.githubusercontent.com/aureliojargas/clitest"
  - curl -sOL "${url_base}/master/clitest"
  - chmod +x clitest
  - mv clitest testador

script:
  - cd testador && ./run zzcores.sh

notifications:
  email: false
